#!/bin/bash

agent_socket=`gpgconf --list-dirs | grep '^agent-socket:' | cut -d ':' -f 2`

if [ -S "$agent_socket" ]; then
    lsof -F p "$agent_socket" 2>/dev/null | grep '^p' | cut -b 2- | xargs -r kill
    rm -f "$agent_socket"
fi

socat "UNIX-LISTEN:$agent_socket,fork" EXEC:/usr/share/split-gpg2/split-gpg2-client-wrapper
